package Settings;
	use constant{
		SIZE_MAIN_WINDOW => "200x400+0+0",
		BACKGROUND => "lavender", 
		RELIEF_BUTTON => 'sunken', 
		BUTTON_BACKGROUND => '#7f83ff', 
		BUTTON_ACTIVEBACKGROUND => '#b8bdff', 
		BACKGROUND_REMOTE_WORD => "red",
		FOREGROUND_REMOTE_WORD => "red",
		BUTTON_BORDERWIDTH => 5, 
		LABEL_BORDERWIDTH => 3,
		BUTTON_OKAY => "Ok",
		BUTTON_CANCEL => "Cancel",
		SIDE_LAB_ENTRY => "left",
		ANCHOR_SCROLLBARS => "se",
		WIDTH_ENTRY_TEXT_FIELD => 25,
		HEIGHT_ENTRY_TEXT_FIELD => 25,
		CURSOR => "hand2", 
		FOREGROUND => "navy blue", 
		ICON => "resources/crossword.gif", 
		LOCALIZATION_POD_FILENAME_APPLICATION => "resources/crossword.pod",
		LOCALIZATION_POD_FILENAME_GEOMETRY_CROSSWORD => "resources/geometry.pod",
		LOCALIZATION_DB_FILENAME => "resources/title.db",
		FILE_WITH_CROSSWORDS => "resources/all_crosswords.db",
		DEFAULT_ROWS => 10,
		DEFAULT_COLUMNS => 10,
		BACKGROUND_WORD => "black",
		BACKGROUND_FIELD => "white",
		FOREGROUND_WORD => "white",
		FOREGROUND_FIELD => "black",
		INITIAL_IMAGE => "resources/cat_cage.gif",
		TARGET_IMAGE => "resources/cat_grumpy.gif",
		ERROR_ICON => "error",
		VALUE_RADIOBUTTON_SET_FILE => 1,
		VALUE_RADIOBUTTON_ENTER_WORDS => 0,
		WIDTH_LAB_ENTRY => 10,
		WIDTH_LAB_ENTRY_COORDINATES => 2,
		ANCHOR_LAB_ENTRY_COORDINATES => "n",
		RELIEF_CELLS_TABLE => "groove",
		PADX_CELLS_TABLE => 2,
		FIXED_ROWS_TABLE => 1,
		YES => 1,
		NO => 0,
		DEFAULT_LANGUAGE => "Russian",
		MAIN_IMAGE => "resources/main_image.gif",
		FILL_IMAGE => "both"
	};				 
1;